export * from "./createSpecialist.service"
export * from "./deletedSpecialist.service"
export * from "./getAllSpecialist.service"
export * from "./getByCorreoSpecialis.service"
export * from "./updateSpecialist.service"